
---
title: "20190502"
author: "AB/CP"
output:
  html_document:
    toc_float: true
    toc: true
    number_sections: true
    theme: united
bibliography: uvpd.bib
vignette: |
  %\VignetteIndexEntry{Analyze - extract - match - aggregate}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load

```{r}
library(uvpd)

load(file.path(system.file(package = 'uvpd'), "/extdata/extractedMs2Feature.RData"))
ls()
```

```{r}
library(ggplot2)
sanityCheckXIC <- function(S, mZoffset=1.007){
  lapply(S, function(x){
    XICs <- readXICs(rawfile = unique(x$rawfile), masses = unique(x$mass) + mZoffset, tol = 30)
    plot.XICs(XICs) + labs(subtitle = basename(unique(x$rawfile)))
  })}
```

```{r}
sanityCheckXIC(uvpd.DBP, mZoffset=1.007)
```

```{r}
sanityCheckXIC(uvpd.Castell, mZoffset=1.007)
```

```{r}
sanityCheckXIC(uvpd.KWRpos, mZoffset=1.007)
```

```{r eval=FALSE}
sanityCheckXIC(uvpd.KWRneg, mZoffset = -1.007)
```

# Sanity checks

```{r}
sapply(uvpd.Castell, nrow)
sapply(uvpd.DBP, nrow)
uvpd.KWRneg <- uvpd.KWRneg[!sapply(uvpd.KWRneg, is.null)]
sapply(uvpd.KWRneg, nrow)
sapply(uvpd.KWRpos, nrow)
```

# Overview plots

## Castell
```{r fig.retina=3, fig.height=12, fig.width=19}
library(lattice)
xyplot(log(intensity, 10) ~ mZ |  formula0 * scanTypeFilter,
       data = do.call('rbind', uvpd.Castell),
       groups = type,
        main = "Castell",
       type ='h')
```

## DBP
```{r fig.retina=3, fig.height=12, fig.width=19}
table(do.call('rbind', uvpd.DBP)$formula0)

xyplot(log(intensity, 10) ~ mZ |  formula0 * scanTypeFilter,
       data = do.call('rbind', uvpd.DBP),
       groups = type,
        main = "DBP",
       type ='h')
```

## KWR pos

```{r fig.retina=3, fig.height=12, fig.width=19}
library(lattice)
xyplot(log(intensity, 10) ~ mZ |  formula0 * scanTypeFilter,
       data = do.call('rbind', uvpd.KWRpos),
       groups = type,
        main = "KWR pos",
       type ='h')
```


## KWR neg

```{r fig.retina=3, fig.height=12, fig.width=19}
library(lattice)
xyplot(log(intensity, 10) ~ mZ |  formula0 * scanTypeFilter,
       data = do.call('rbind', uvpd.KWRneg),
       groups = type,
       main = "KWR nreg",
       type ='h')
```
