---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Load

```{r}
library(uvpd)
load(file.path(system.file(package = 'uvpd'), "/extdata/extractedMs2Feature.RData"))

# load(file.path(system.file(package = 'uvpd'), "/extdata/fragments.RData"))
#
# rawfiles <- scan(file.path(system.file(package = 'uvpd'),
#                            "/extdata/rawfiles.txt"), what = character())
# rawfiles <- rawfiles[grepl("Castell|KWR|DB", rawfiles)]


```

```{r}
#R

# estimate the number of centroid peaks
estCentroidPeaks <- function(S, eps = 1 / 200){

        idx <- (S$intensity > 0)
        S$mZ <- S$mZ[idx]
        S$intensity <- S$intensity[idx]

        n <- length(S$mZ)
        cluster <- rep(0, n)
        counter <- 1
        cluster[1] <- counter
        cmZ <- S$mZ[1]

        for (i in 2:n){

                intensity.max <- max(S$intensity)

                d <- abs(cmZ - S$mZ[i])
                #print(d)

                if (d < eps & S$intensity[i] > 0){
                } else {
                        counter <- counter + 1
                }
                cluster[i] <- counter
                cmZ <- S$mZ[i]
        }
         #idx <- (cluster %in% which(table(cluster) > 3))
        S$mZ <- aggregate(S$mZ ~ cluster, FUN=median)[,2]
        S$sumintensity <- aggregate(S$intensity ~ cluster, FUN=sum)[,2]
        S$intensity <- aggregate(S$intensity ~ cluster, FUN=max)[,2]
        S
}
```

```{r run}
xxx <- function(x){
  rawfile <- x$rawfile[1]
  scans <- unique(x$scan)
  
  df <- unique(data.frame(scan=x$scan, nMS2=x$nMS2))
  
  S.profile <- readScans(rawfile, df$scan)
  
  S.centroid <- lapply(S.profile, estCentroidPeaks, eps=1/1000)
  
  df$npeaks.profile <- sapply(S.profile, function(y){length(y$mZ)})
  
  df$npeaks.centroid <- sapply(S.centroid, function(y){length(y$mZ)})
  df$rawfile <- rawfile
  
  df
  
}
```


```{r}
# library(uvpd)
load(file.path(system.file(package = 'uvpd'), "/extdata/extractedMs2Feature.RData"))
rv <- lapply(uvpd.Castell, xxx)

S <- (do.call('rbind', rv))
plot(S$nMS2, S$npeaks.centroid, pch=16, col=as.factor(S$rawfile), cex=1.4)
```


## Summary

```{r}
Smatch <- do.call('rbind', lapply(uvpd.Castell, function(x){aggregate(intensity ~ SMILES0 * rawfile * scanTypeFilter*  scan, data=x, FUN=length)}))

names(Smatch) <- c("SMILES0",   "rawfile", "scanTypeFilter",  "scan",      "nPSM")

uvpd.Castell.summary <- merge(S, Smatch)

table(uvpd.Castell.summary$nMS2 > uvpd.Castell.summary$npeaks.centroid)
table(uvpd.Castell.summary$nPSM > uvpd.Castell.summary$npeaks.centroid)

```


## Boxplot

```{r}
boxplot( uvpd.Castell.summary$nPSM / uvpd.Castell.summary$npeaks.centroid ~ uvpd.Castell.summary$scanTypeFilter)
```

### csv file with SMILES
```{r preparation}

library(readr)


ThermoUVPD_feb2019 <- read_csv(file.path(system.file(package = 'uvpd'),
                                         "/extdata/ThermoUVPD_feb2019.csv"))


rv <- merge(uvpd.Castell.summary,
            ThermoUVPD_feb2019[,c('Cluster number', 'SMILES')],
            by.x = "SMILES0", by.y = "SMILES")

boxplot(nPSM / npeaks.centroid ~ scanTypeFilter, data=rv)

 dotplot(nPSM / npeaks.centroid ~scanTypeFilter, data=rv, group=rv$`Cluster number`, scales = list(x = list(rot = 45)), auto.key = list(space = "right"))

dotplot(nPSM / npeaks.centroid ~ scanTypeFilter | SMILES0,
        data=rv,
        group=rv$`Cluster number`,
        scales = list(x = list(rot = 45)),
        auto.key = list(space = "right"),
        pch=16,
        layout=c(3, 4))

dotplot(nPSM / npeaks.centroid ~ substr(SMILES0, 1, 20) | scanTypeFilter ,
        data=rv,
        group=rv$`Cluster number`,
        scales = list(x = list(rot = 45)),
        auto.key = list(space = "right"),
        pch=16,
        index.cond=list(c(1:3, 7,11,4,5,6,8,9,10,12,13)))

dotplot(nPSM / nMS2 ~ substr(SMILES0, 1, 20) | scanTypeFilter ,
        data=rv,
        group=rv$`Cluster number`,
        scales = list(x = list(rot = 45)),
        auto.key = list(space = "right"),
        pch=16,
        index.cond=list(c(1:3, 7,11,4,5,6,8,9,10,12,13)))
```

