---
title: "ASMS 2019 poster figures"
author: "AB/CP"
output:
  html_document:
    toc_float: true
    toc: true
    number_sections: true
    theme: united
bibliography: uvpd.bib
---


# Input

## in-silico

```{r}
library(metfRag)

smiles <- "CC(C)(C)C(O)C(OC1=CC=C(Cl)C=C1)N1C=NC=N1"
molecule<-parse.smiles(smiles)[[1]]

#calculate the fragments
fragments <- frag.generateFragments(molecule, 1)

length(fragments)

```

## Mass Spec Data
 
```{r}
library(uvpd)
library(rawDiag)
#rawfile <- "/Users/cp/data/stds_pos_neg_MS_highconc_UVPD_50_300.raw"
(rawfile <- file.path(Sys.getenv('HOME'), "Downloads",
  "stds_pos_neg_MS_highconc_UVPD_50_300.raw"))
#rawfile <- "/srv/www/htdocs/p2722/Proteomics/LUMOS_0/Thermo_feb2019/20190214/CastellonStds/CastellonStds_pos_HCD_20_35_60.raw"


#rawfile <- "/srv/www/htdocs/p2722/Proteomics/LUMOS_0/Thermo_feb2019/20190214/CastellonStds/CastellonStds_pos_UVPD_400_500.raw"
rawfile <- "/srv/www/htdocs/p2722/Proteomics/LUMOS_0/Thermo_feb2019/20190213/7stds/stds_pos_neg_MS_highconc_UVPD_100_150_mz50.raw"
```




# XIC

```{r}
do.isotopes(molecule)
(mZ <- get.exact.mass(molecule) + 1.007)


XIC <- readXICs(rawfile, mZ, tol=30)
```

```{r ASMS_XIC, fig.retina=3, fig.path='./graphics/'}
#library(ggplot2)
#plot(XIC) + 
#  labs(x = "Retention Time [min]", y = "Intensity") +
#  labs(subtitle = smiles)
library(lattice)
xyplot(intensities ~ times, data=XIC[[1]] ,
       type='b',
       xlab='Retention Time [min]',
       lwd=2,
       ylab='Intensity',
       sub=paste("XIC of ", smiles))
```


# in-silico fragment ions
example call

```{r computeIn-silicoFragments}
df.frags <- getFragments("CC(C)(C)C(O)C(OC1=CC=C(Cl)C=C1)N1C=NC=N1", treeDepth = 1) 
df.frags <- df.frags[!is.na(df.frags$mZ), ]

```

## Plot in-silico spec
```{r ASMS_in-silico-fragmentIons, fig.retina=3, fig.path='./graphics/'}
#plot(0,0, xlim=range(f.mZ<-unique(df.frags$mZ)), ylim=c(0,1), type = 'n', xlab = 'mZ', ylab=''); abline(v=df.frags$mZ, col=df.frags$type)
library(lattice)
xyplot(rep(1, nrow(df.frags)) ~ mZ,
       data=df.frags,
       group=type,
       type='h',
       ylim=c(0,1),
       auto.key = TRUE,
       sub=paste("in-silico fragment ions of ", smiles),
       ylab='Intensity')
```

# Castell match
```{r ASMS_Castell, fig.retina=3, fig.height=12, fig.width=19, fig.path='./graphics/'}

library(uvpd)

load(file.path(system.file(package = 'uvpd'), "/extdata/extractedMs2Feature.RData"))




xyplot(log(intensity, 10) ~ mZ |  formula0 * scanTypeFilter,
       data = do.call('rbind', uvpd.Castell),
       groups = type,
       auto.key = TRUE,
       main = "Castell",
       index.cond=list(1:10,c(1:3, 7,11,4,5,6,8,9,10,12,13)),
       type ='h')
```


