
---
title: "20190425"
author: "AB/CP"
output:
  html_document:
    toc_float: true
    toc: true
    number_sections: true
    theme: united
bibliography: uvpd.bib
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load

```{r}
library(uvpd)
load(file.path(system.file(package = 'uvpd'), "/extdata/fragments.RData"))
# load("~/__checkouts/R/uvpd/inst/extdata/uvpd-Meuse.RData")
rawfiles <- scan(file.path(system.file(package = 'uvpd'),
                           "/extdata/rawfiles.txt"), what = character())
rawfiles <- rawfiles[grepl("Castell|KWR|DB", rawfiles)]

```


# Extract XICs

```{r message=TRUE}
.assignAPEX <- function(rawfile, fragments, mZoffset=1.007, method='rt', tolppm=30){
 
  XIC <- readXICs(rawfile, fragments$mass + mZoffset, tol = tolppm)
  n <- length(fragments$mass)
  stopifnot(length(XIC) == n)

  fragments$rt.max <- rep(NA, n)
  fragments$intensity.max <-rep(NA, n)
  fragments$rawfile <- rawfile
  
  for (i in 1:n){
    try({
      
      if ("intensities" %in% names(XIC[[i]]) & length(XIC[[i]]$intensities) > 0){
        intensity.max <- max(XIC[[i]]$intensities, na.rm = TRUE)
        
        if (intensity.max < 1000 || 
            length(XIC[[i]]$intensities) < 6 || 
            5 * median(XIC[[i]]$intensities) > intensity.max){
          
        }else{
          
          fragments$rt.max[i] <- XIC[[i]]$times[which(intensity.max == XIC[[i]]$intensities)[1]]
          fragments$intensity.max[i] <- intensity.max
        }
        
      }
    })
  }
  
  fragments
}
```

```{r message=TRUE}
.assignMatchedFragmentIons <- function(fragments, mZoffset=1.007, eps.mZ = 0.05,
                                       eps.rt = 0.5, scanTypeFilter = "", ...){
  n <- length(fragments$mass)
  
  RAW <- read.raw(fragments$rawfile)
  RAW <- RAW[RAW$MSOrder == "Ms2", ]
  
  res <- lapply(which(!is.na(fragments$rt.max)), function(i){
    #print(i)
    mz <- fragments$mass[i] + mZoffset
    rt.max <- fragments$rt.max[i] 
    
    filter <- grepl(scanTypeFilter, RAW$ScanType) &
      mz - eps.mZ < RAW$PrecursorMass & 
      RAW$PrecursorMass <  mz + eps.mZ &
      rt.max - eps.rt < RAW$StartTime &
      RAW$StartTime <= rt.max + eps.rt
  
    
    if (sum(filter) > 0){
      scans <- RAW$scanNumber[filter]
   
      MS2Scans <- uvpd:::.filterMS2Scans(readScans(fragments$rawfile, scans))
     
      df <- uvpd::matchFragment(MS2Scans, fragments = na.omit(fragments$ms2[[i]]), ...)
      df$rawfile <- fragments$rawfile
      df$scanTypeFilter <- scanTypeFilter
      df$SMILE0 <- fragments$SMILES[i]
      df$mass <- fragments$mass[i]
      df$n <- length(scans)
      df
    }
  })
}

```


```{r message=TRUE}

fun <- function(rawfile=rawfiles[20]){
  
  X <- .assignAPEX(rawfile, fragments.treeDepth1)

  scanTypes <- uvpd:::.getScanType(rawfile)
  
  XX <- lapply(scanTypes, function(st){.assignMatchedFragmentIons(X, scanTypeFilter = st, FUN=sum)})
  
  XX
}

funfun<-function(rawfile){
  xx <- fun(rawfile)
  xxx <- do.call('rbind', lapply(xx, function(x){do.call('rbind',x[sapply(x, length) == 10])}))
}

X <- mclapply(rawfiles, funfun, mc.cores=24)
```

```{r extractXICs, eval=FALSE}
library(parallel)
X <- mclapply(rawfiles[24:34], FUN = .assignAPEX, fragments=fragments.treeDepth1, mZoffset=1.007, mc.cores = 4)
#XX <- mclapply(X, FUN=.assignMatchedFragmentIons)
```

 

## Read Input



```{r, eval=FALSE}

uvpd.summary <- function(object, ...){
    
   list(
        sum=aggregate(log(intensity, 10) ~  scanTypeFilter * SMILES0 * rawfile , data=object, FUN=sum),
    length=aggregate(log(intensity, 10) ~  scanTypeFilter * SMILES0 * rawfile , data=object, FUN=length),
     quantile=aggregate(log(intensity, 10) ~  scanTypeFilter * SMILES0 * rawfile , data=object, FUN=quantile)
    )
}
```


```{r fig.retina=3, fig.width=19, fig.height=12, eval=FALSE}
KWRpos <- lapply(rawfiles[grepl("KWR.+(HCD|UVPD)", rawfiles)], analyze, smiles=ThermoUVPD_feb2019$SMILES)
lapply(KWRpos, function(x){try(uvpd.summary(x))})
    
KWRneg <- lapply(rawfiles[grepl("KWR.+(HCD|UVPD)", rawfiles)], analyze, smiles=ThermoUVPD_feb2019$SMILES, mZoffset=-1.007)
```