---
title: "Computer in-silico fragment and match"
author: "AB/CP"
output:
  html_document:
    toc_float: true
    toc: true
    number_sections: true
    theme: united
bibliography: uvpd.bib
---

# 2019-03-14 

session @ fgcz, AB/CP

- site note: Metabolmics 


TODO:

- MetFragR R package https://github.com/ipb-halle/MetFragR
  * compute in-silico fragments (CP)
  
https://github.com/ipb-halle/MetFragR/blob/9e482f6f6cb3cb6aa07af779d9acc7d6ff757f5f/metfRag/R/fragment.R#L11


```{r}
library(metfRag)

smiles <- "CC(C)(C)C(O)C(OC1=CC=C(Cl)C=C1)N1C=NC=N1"
molecule<-parse.smiles(smiles)[[1]]

#calculate the fragments
fragments <- frag.generateFragments(molecule, 1)

length(fragments)

```

- Input: 
 
 
```{r}
library(uvpd)
library(rawDiag)
#rawfile <- "/Users/cp/data/stds_pos_neg_MS_highconc_UVPD_50_300.raw"
(rawfile <- file.path(Sys.getenv('HOME'), "Downloads",
  "stds_pos_neg_MS_highconc_UVPD_50_300.raw"))
RAW <- read.raw(rawfile, rawDiag = TRUE)
```


```{r}
 table(RAW$MSOrder)
```


## Input


### Get XIC

```{r}
mz <- 296.116

# alternative
do.isotopes(molecule)
get.exact.mass(molecule) + 1.007


XIC <- readXICs(rawfile, mz)

plot(XIC)
```

### Get Ms2 Scannumbers

```{r}
```

### Get Ms2 Scans


```{r}
plot.MS2Scans <- function (x, y, ...) 
{
    plot(x$mZ, x$intensity, type = "h", main = x$title, xlab = "m/Z", 
        ylab = "intensity", 
        sub=x$scanType,
        ...)
}



queryScannumbers <- sn[RAW$StartTime[sn] * 60 > 951 & RAW$StartTime[sn] * 60  < 961]
MS2Scans <- readScans(rawfile = rawfile, queryScannumbers)
#lapply(MS2Scans, plot.MS2Scans)
```

# 2019-03-26 
1415-1600 via Skype, FGCZ


## Implement getFragments method

```{r}
getFragments
```

example call

```{r computeIn-silicoFragments}
df.frags <- getFragments("CC(C)(C)C(O)C(OC1=CC=C(Cl)C=C1)N1C=NC=N1", treeDepth = 1) 
df.frags <- df.frags[!is.na(df.frags$mZ), ]

```

### Plot in-silico spec
```{r in-silico, fig.retina=3}
plot(table(df.frags$mZ))
```


## Compute and Plot Matches

```{r matchPlot, fig.retina=3}
# table.df.frags <- table(df.frags$mZ)

library(protViz)
library(knitr)

write.csv(file='peaklist1.csv', data.frame(mZ=MS2Scans[[1]]$mZ, 
                                           intensity=MS2Scans[[1]]$intensity),
          row.names = FALSE)
```

```{r MS2filtering}
# filtering 

.filterMS2Scans <- function(y, ...){
  lapply(y,
         function(x){
           rv <- x; 
           idx <- x$intensity > 0; 
           x$mZ <- x$mZ[idx]; 
           x$intensity <- x$intensity[idx]; 
           x})
}

MS2Scans <- .filterMS2Scans(MS2Scans)

```


```{r match}
rv.match <- matchFragment(MS2Scans, fragments = df.frags, FUN=sum)
kable(rv.match)
```


# 20190415 Analysis

```{r preparation}
library(readr)
library(uvpd)

ThermoUVPD_feb2019 <- read_csv(file.path(system.file(package = 'uvpd'),
                                         "/extdata/ThermoUVPD_feb2019.csv"))

names(ThermoUVPD_feb2019)
molecules <- lapply(ThermoUVPD_feb2019$SMILES, function(x){
  mol <- parse.smiles(x)[[1]]; do.isotopes(mol); mol})

mass <-  sapply(molecules, FUN=get.exact.mass) + 1.007


mass.smiles <- data.frame(mass=mass, smiles=ThermoUVPD_feb2019$SMILES)
```

```{r extractXICs, eval=FALSE}
library(ggplot2)
library(parallel)
library(uvpd)
rawfiles <- scan(file.path(system.file(package = 'uvpd'),
                           "/extdata/rawfiles.txt"), what = character())
rawfiles <- rawfiles[grepl("Castell|KWR|DB", rawfiles)]
#rawfiles <- rawfiles[grepl("KWR", rawfiles)]

rawfiles <- rawfiles[!grepl("blank_", rawfiles)]
rawfiles <- rawfiles[!grepl("Blank_", rawfiles)]
rawfiles <- rawfiles[file.exists(rawfiles)]

xxxx <- function(rawfile, mass, method='rt'){
  
  XIC <- readXICs(rawfile, mass, tol = 30)
  
  # filter
  XIC <- lapply(XIC, function(x){
    if (max(x$intensities) < 1000 || 
        length(x$intensities) < 6 || 
        5 * median(x$intensities)> max(x$intensities)){
      return (NULL)
    }
    
    x
  })
  
  XIC <- XIC[which(!sapply (XIC, is.null))]
  
  if(method=='plot'){
  gp <- plot.XICs(XIC) + facet_wrap(~ mass, scales = "free") + labs(title = rawfile)
  # pdf(paste("/tmp/uvpd--", basename(rawfile),".pdf", sep=''), 19,12)
  print(gp)
  }else{
    rv <- lapply(XIC, function(x){
      data.frame(mass=x$mass,
      rt.max=x$times[which(max(x$intensities) == x$intensities)[1]])
    })
    do.call('rbind', rv)
  }
  # dev.off()
}


pdf("/tmp/uvpd2.pdf", 19,12)
rv <- lapply(rawfiles, function(rawfile){
 rv <- try(xxxx(rawfile, mass=mass))
 rv$rawfile <- rawfile
 rv
})
dev.off()


```

## extract scan numbers 
```{r}

.extractScanNumbers <- function(x, eps.mZ = 0.05, eps.rt=0.5, df, ...){
  rawfile <- x$rawfile[1]
  
  RAW <- read.raw(rawfile)
  RAW <- RAW[RAW$MSOrder == "Ms2", ]
  
  rv <- lapply(1:length(x$mass), function(i){
   
    mz <- x$mass[i]
    
    rt.max <- x$rt.max[i] 
    
    filter <- mz - eps.mZ < RAW$PrecursorMass & 
      RAW$PrecursorMass <  mz + eps.mZ &
      rt.max - eps.rt < RAW$StartTime &
      RAW$StartTime <= rt.max + eps.rt
    
    sn <-RAW$scanNumber[filter]
    
    
    # df <- data.frame(scanNumber=sn, error.mZ=abs(RAW$PrecursorMass[filter]-mz))
    
    if(length(sn) > 0){
       print(paste("id", i))
      MS2Scans <- .filterMS2Scans(readScans(rawfile, sn))
      smiles <- as.character(droplevels(mass.smiles$smiles[abs(mass.smiles$mass - mz) < 0.001]))[1]
      print(smiles)
      
      df.frags <- getFragments(smiles, treeDepth=1)
      df.frags <- na.omit(df.frags)
      
      print(length(MS2Scans))
      print(dim(df.frags))
      
      rv.match <- matchFragment(MS2Scans, fragments = df.frags, FUN=sum)
      
      print(dim(rv.match))
      if(!is.null(rv.match)){
        
        rv.match$rawfile <- rawfile
        rv.match$mass <- mz
        rv.match$rt.max <- rt.max
        rv.match$SMILES0 <- smiles
        rv.match$nMS2Scans <- length(sn)
        print("---")
        return(rv.match)}
      }
    return (NULL)
  })
  do.call('rbind', rv)
 #rv
}
```

```{r numberCrunching}
S <- lapply(rv, function(x){try(.extractScanNumbers)})
#S <- do.call('rbind', mclapply(rv, .extractScanNumbers, mc.cores=4))
```

```{r xyplot, fig.retina=3, fig.height=10, fig.width=24}
SS <- do.call('rbind', S)
xyplot(log(intensity,10) ~ mZ | SMILES0 * basename(rawfile), groups = type, data=SS, type='h')
```

