---
title: "supplements"
author: "AB/CP"
date: "5/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Compose

* run `20200416.R`

```{r eval=FALSE}
library(readr)
file_group <- read_csv("file-group.csv")
FG <- file_group[paste(file_group$file, ".raw",sep='') %in% X20200423_uvpd$filename, ]
FG$file <- paste(FG$file, '.raw', sep='')


GS <- data.frame(group=ThermoUVPD_feb2019$Group, SMILES=ThermoUVPD_feb2019$SMILES)
GSF <- merge(GS, FG, by='group')

X20200423_uvpd$m <- paste(X20200423_uvpd$filename, X20200423_uvpd$SMILES)

GSF$m <- paste(GSF$file, GSF$SMILES)


X20200423 <- merge(GSF, X20200423_uvpd, by='m')

```


## Load
```{r}
load(file.path(system.file(package = 'uvpd'), "/extdata/X20200423.RData"))
```


## Sanity check

negative mode

```{r}
knitr::kable(table(X20200423$file[X20200423$mode < 0], X20200423$Group[X20200423$mode < 0]))
```

one substance seems to be part of multiple groups!

positive mode

```{r}
knitr::kable(table(X20200423$file[X20200423$mode > 0], X20200423$Group[X20200423$mode > 0]))
```

lets exclude `"4-Chlorobenzoic acid"`

```{r}
X <- X20200423[!(X20200423$Compound=="4-Chlorobenzoic acid"), ]
knitr::kable(table(X$file[X$mode < 0], X$Group[X$mode < 0]))
knitr::kable(table(X$file[X$mode > 0], X$Group[X$mode > 0]))
```

```{r}
xyplot(log(tic) ~ log(master.intensity) | Compound, groups = fragmode, data=X20200423, pch='.')
```

```{r}
knitr::kable(head(X))
```
master intensity =def= masterscan (MS1) isolated precursor m/z intensity in a given mass window +- 0.01 Da.

find three best matches acc. highest master intensity

```{r determinetop3}
# theoretic possible combinations
cc <- expand.grid(as.character(unique(X$file)), as.character(unique(X$SMILES.x)), as.character(unique(X$fragmode)))
names(cc) <- c('file', 'SMILES', 'fragmode')
cc <- paste(cc$file, cc$SMILES, cc$fragmode)

# this is the real world
X$m <- paste(X$file, X$SMILES.x, X$fragmode)

 library(parallel)
X.top3.master.intensity <- do.call('rbind', lapply(cc, function(m){
    XX <- X[X$m == m, ]
    XX <- XX[order(XX$master.intensity, decreasing = TRUE), ]
    n <- nrow(XX)
    
    if (nrow(XX) > 2){
        return(XX[1:3, ])}
    else if (n > 0){
        return(XX[1:n, ])}
    else{return(NULL)}
}))

X.top3.tic <- do.call('rbind', lapply(cc, function(m){
    XX <- X[X$m == m, ]
    XX <- XX[order(XX$tic, decreasing = TRUE), ]
    n <- nrow(XX)
    
    if (nrow(XX) > 2){
        return(XX[1:3, ])}
    else if (n > 0){
        return(XX[1:n, ])}
    else{return(NULL)}
}))

```

```{r}
table(X.top3$file)
table(X.top3$SMILES.x)
table(X.top3$fragmode)
```

```{r}
image(as.matrix(table(X.top3$file, X.top3$fragmode)))
```


compare pos versus negative
TODO(CP): order by reacion time / ce
```{r}
library(lattice);

lp <- bwplot(log(master.intensity / tic) ~ as.character(mode) | as.factor(fragmode), 
        data=X.top3.master.intensity, horizontal = F)

lp <- bwplot(log(master.intensity / tic) ~ as.character(mode) | as.factor(fragmode), 
        data=X.top3.tic, horizontal = F)
```

```{r}
plot(X.top3.tic$scan , X.top3.master.intensity$scan)
```


